import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { DM_Mono } from "next/font/google";

import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = DM_Mono({
  subsets: ["latin"],
  display: "swap",
  weight: ["300","400", "500"]
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
