-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T19:05:04.342Z

REVOKE INSERT ON TABLE private_tables."Genre" FROM "group:customer";
REVOKE DELETE ON TABLE private_tables."Genre" FROM "group:customer";
REVOKE UPDATE ON TABLE private_tables."Genre" FROM "group:customer";
REVOKE SELECT ON TABLE private_tables."Genre" FROM "group:customer";