-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-07T18:10:39.779Z

REVOKE USAGE ON SCHEMA "public_views" FROM "customer:xyz";
REVOKE USAGE ON SCHEMA "public_views" FROM "group:customer";