-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T14:19:01.969Z

REVOKE EXECUTE ON FUNCTION private_tables.asterisks(integer,integer) FROM "public";
REVOKE EXECUTE ON FUNCTION private_tables.add(integer,integer) FROM "authenticated";
GRANT EXECUTE ON FUNCTION private_tables.asterisks(integer,integer) TO "authenticated";