-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T14:21:46.934Z

GRANT EXECUTE ON FUNCTION private_tables.asterisks(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION private_tables.asterisks(integer,integer) TO "authenticated";