-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T15:38:09.881Z

REVOKE EXECUTE ON FUNCTION private_tables.asterisks(integer,integer) FROM "authenticated";
REVOKE EXECUTE ON FUNCTION private_tables.asterisks(integer) FROM "authenticated";