-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T16:15:28.944Z

REVOKE EXECUTE ON FUNCTION private_tables.asterisks(n integer, n2 integer) FROM "authenticated";
REVOKE EXECUTE ON FUNCTION private_tables.asterisks(n integer) FROM "authenticated";