-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-09T18:04:03.858Z

REVOKE INSERT ON TABLE private_tables."Album" FROM "postgres";
REVOKE TRIGGER ON TABLE private_tables."Album" FROM "postgres";
REVOKE SELECT ON TABLE private_tables."Album" FROM "postgres";
REVOKE UPDATE ON TABLE private_tables."Album" FROM "postgres";
REVOKE DELETE ON TABLE private_tables."Album" FROM "postgres";
REVOKE TRUNCATE ON TABLE private_tables."Album" FROM "postgres";
REVOKE REFERENCES ON TABLE private_tables."Album" FROM "postgres";