-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-10T18:52:17.191Z

GRANT TRIGGER ON TABLE private_tables."Employee" TO "postgres";
GRANT INSERT ON TABLE private_tables."Employee" TO "postgres";
GRANT SELECT ON TABLE private_tables."Employee" TO "postgres";
GRANT UPDATE ON TABLE private_tables."Employee" TO "postgres";
GRANT DELETE ON TABLE private_tables."Employee" TO "postgres";
GRANT TRUNCATE ON TABLE private_tables."Employee" TO "postgres";
GRANT REFERENCES ON TABLE private_tables."Employee" TO "postgres";