-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-10T18:53:01.695Z

REVOKE TRIGGER ON TABLE private_tables."Employee" FROM "postgres";
REVOKE INSERT ON TABLE private_tables."Employee" FROM "postgres";
REVOKE SELECT ON TABLE private_tables."Employee" FROM "postgres";
REVOKE UPDATE ON TABLE private_tables."Employee" FROM "postgres";
REVOKE DELETE ON TABLE private_tables."Employee" FROM "postgres";
REVOKE TRUNCATE ON TABLE private_tables."Employee" FROM "postgres";
REVOKE REFERENCES ON TABLE private_tables."Employee" FROM "postgres";