-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T02:47:39.469Z

REVOKE SELECT ON TABLE "private_tables"."Artist" FROM "customer:xyz";
REVOKE DELETE ON TABLE "private_tables"."Artist" FROM "postgres";
REVOKE UPDATE ON TABLE "private_tables"."Artist" FROM "postgres";
