-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:00:10.670Z

REVOKE TRIGGER ON TABLE "private_tables"."Employee" FROM PUBLIC;
REVOKE REFERENCES ON TABLE "private_tables"."Employee" FROM PUBLIC;
REVOKE TRUNCATE ON TABLE "private_tables"."Employee" FROM PUBLIC;
REVOKE DELETE ON TABLE "private_tables"."Employee" FROM PUBLIC;
REVOKE UPDATE ON TABLE "private_tables"."Employee" FROM PUBLIC;
REVOKE INSERT ON TABLE "private_tables"."Employee" FROM PUBLIC;
REVOKE SELECT ON TABLE "private_tables"."Employee" FROM PUBLIC;
GRANT TRIGGER ON TABLE "private_tables"."Employee" TO "customer:xyz";
GRANT REFERENCES ON TABLE "private_tables"."Employee" TO "customer:xyz";
GRANT TRUNCATE ON TABLE "private_tables"."Employee" TO "customer:xyz";
GRANT DELETE ON TABLE "private_tables"."Employee" TO "customer:xyz";
GRANT UPDATE ON TABLE "private_tables"."Employee" TO "customer:xyz";
GRANT INSERT ON TABLE "private_tables"."Employee" TO "customer:xyz";
GRANT SELECT ON TABLE "private_tables"."Employee" TO "customer:xyz";