-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:02:50.564Z

REVOKE INSERT ON TABLE "private_tables"."Employee" FROM "customer:xyz";
REVOKE TRUNCATE ON TABLE "private_tables"."Employee" FROM "customer:xyz";
REVOKE DELETE ON TABLE "private_tables"."Employee" FROM "customer:xyz";
REVOKE UPDATE ON TABLE "private_tables"."Employee" FROM "customer:xyz";
REVOKE SELECT ON TABLE "private_tables"."Employee" FROM "customer:xyz";
REVOKE REFERENCES ON TABLE "private_tables"."Employee" FROM "customer:xyz";
REVOKE TRIGGER ON TABLE "private_tables"."Employee" FROM "customer:xyz";