-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:06:38.849Z

REVOKE INSERT ON TABLE "public_views"."customers" FROM "postgres";
REVOKE SELECT ON TABLE "public_views"."customers" FROM "postgres";
REVOKE UPDATE ON TABLE "public_views"."customers" FROM "postgres";
REVOKE DELETE ON TABLE "public_views"."customers" FROM "postgres";
REVOKE TRUNCATE ON TABLE "public_views"."customers" FROM "postgres";
REVOKE REFERENCES ON TABLE "public_views"."customers" FROM "postgres";
REVOKE TRIGGER ON TABLE "public_views"."customers" FROM "postgres";