-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:13:26.270Z

REVOKE USAGE ON SEQUENCE "private_tables"."seq" FROM PUBLIC;
REVOKE SELECT ON SEQUENCE "private_tables"."seq" FROM PUBLIC;
REVOKE UPDATE ON SEQUENCE "private_tables"."seq" FROM PUBLIC;
REVOKE UPDATE ON SEQUENCE "private_tables"."seq" FROM "authenticated";
REVOKE SELECT ON SEQUENCE "private_tables"."seq" FROM "authenticated";
REVOKE USAGE ON SEQUENCE "private_tables"."seq" FROM "authenticated";
REVOKE SELECT ON SEQUENCE "private_tables"."seq" FROM "postgres";
REVOKE USAGE ON SEQUENCE "private_tables"."seq" FROM "postgres";
REVOKE UPDATE ON SEQUENCE "private_tables"."seq" FROM "postgres";