-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:22:07.076Z

REVOKE EXECUTE ON FUNCTION "private_tables".add(a integer, b integer) FROM "authenticated";
REVOKE EXECUTE ON FUNCTION "private_tables".add(a integer, b integer) FROM "postgres";
REVOKE EXECUTE ON FUNCTION "private_tables".asterisks(n integer) FROM "postgres";
REVOKE EXECUTE ON FUNCTION "private_tables".asterisks(n integer, n2 integer) FROM "postgres";