-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:38:41.253Z

REVOKE CREATE ON DATABASE "totuna" FROM "postgres";
REVOKE TEMPORARY ON DATABASE "totuna" FROM "postgres";
REVOKE CONNECT ON DATABASE "totuna" FROM "postgres";