-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T03:56:15.826Z

REVOKE TRUNCATE ON TABLE "private_tables"."Genre" FROM "postgres";
REVOKE REFERENCES ON TABLE "private_tables"."Genre" FROM "postgres";
REVOKE TRIGGER ON TABLE "private_tables"."Genre" FROM "postgres";