-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T04:35:38.699Z

REVOKE SELECT("AlbumId") ON TABLE "private_tables"."Album" FROM "authenticated";
REVOKE ALL ("ArtistId") ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE ALL ("Title") ON TABLE "private_tables"."Album" FROM PUBLIC;