-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T04:40:51.327Z

REVOKE ALL ("Title") ON TABLE "private_tables"."Album" FROM PUBLIC;
GRANT SELECT ("Title") ON TABLE "private_tables"."Album" TO PUBLIC;