-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T04:41:19.330Z

REVOKE SELECT ("Title") ON TABLE "private_tables"."Album" FROM PUBLIC;
GRANT ALL ("Title") ON TABLE "private_tables"."Album" TO PUBLIC;