-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T04:52:56.341Z

GRANT SELECT ON TABLE "private_tables"."Album" TO PUBLIC;
GRANT UPDATE ON TABLE "private_tables"."Album" TO PUBLIC;
GRANT DELETE ON TABLE "private_tables"."Album" TO PUBLIC;
GRANT INSERT ON TABLE "private_tables"."Album" TO PUBLIC;
GRANT TRIGGER ON TABLE "private_tables"."Album" TO PUBLIC;
GRANT REFERENCES ON TABLE "private_tables"."Album" TO PUBLIC;
GRANT TRUNCATE ON TABLE "private_tables"."Album" TO PUBLIC;