-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-11T04:53:48.092Z

REVOKE REFERENCES ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE SELECT ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE UPDATE ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE DELETE ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE TRUNCATE ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE TRIGGER ON TABLE "private_tables"."Album" FROM PUBLIC;
REVOKE INSERT ON TABLE "private_tables"."Album" FROM PUBLIC;