-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T17:27:09.438Z

GRANT SELECT ON SEQUENCE private_tables."seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE private_tables."seq" TO "authenticated";
GRANT USAGE ON SEQUENCE private_tables."seq" TO "authenticated";