-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-08T17:47:33.018Z

GRANT INSERT ON TABLE private_tables."InvoiceLine" TO "authenticated";
GRANT SELECT ON TABLE private_tables."InvoiceLine" TO "authenticated";