-- Migration generated by @TOTUNA CLI
-- Generated at: 2024-05-09T17:52:28.096Z

REVOKE DELETE ON TABLE private_tables."Genre" FROM "postgres";
REVOKE UPDATE ON TABLE private_tables."Genre" FROM "postgres";
REVOKE INSERT ON TABLE private_tables."Genre" FROM "postgres";
REVOKE SELECT ON TABLE private_tables."Genre" FROM "postgres";