-- Privileges Migration generated by @totuna
  -- Generated at: 2024-05-02T22:03:20.429Z-- Revoke Statements
REVOKE TEMPORARY ON DATABASE totuna FROM postgres;
REVOKE CONNECT ON DATABASE totuna FROM customer:xyz;