-- Privileges Migration generated by @totuna
  -- Generated at: 2024-05-02T18:03:04.260Z-- Revoke Statements
REVOKE TEMPORARY ON DATABASE totuna FROM postgres;
REVOKE CONNECT ON DATABASE totuna FROM user_01hw6n6azyeq2bsa94hgzwyb81;