export * as CRDParser_SchemaPrivileges_YAML from './@CRDParser_SchemaPrivileges_YAML.js'
export * as CRDParser_FunctionPrivileges_YAML from './@CRDParser_FunctionPrivileges_YAML.js'
export * as CRDParser_DatabasePrivileges_YAML from './@CRDParser_DatabasePrivileges_YAML.js'
export * as CRDParser_SequencePrivileges_YAML from './@CRDParser_SequencePrivileges_YAML.js'
export * as CRDParser_TablePrivileges_YAML from './@CRDParser_TablePrivileges_YAML.js'
export * as CRDParser_ViewPrivileges_YAML from './@CRDParser_ViewPrivileges_YAML.js'
export * as CRDParser_TableColumnsPrivileges_YAML from './@CRDParser_TableColumnsPrivileges_YAML.js'
