import {BaseCommand} from './BaseCommand.js'
import * as CRDs from 'CRD/@crds.js'
import * as CRDYAMLParsers from 'CRD/@crdParsers.js'
import fs from 'node:fs'
import path from 'node:path'
import * as glob from 'glob'
import {Table} from 'console-table-printer'

/* -------------------------------------------------------------------------- */
/*                               Command                               */
/* -------------------------------------------------------------------------- */

export default class Command extends BaseCommand<typeof Command> {
  public static enableJsonFlag = true
  static override description = 'Compare current local state with remote state.'
  static override examples = ['<%= config.bin %> <%= command.id %>']

  public async init(): Promise<void> {
    await super.init()
  }

  /* ----------------------------------- run ---------------------------------- */

  public async run() {
    this.log(`\x1b[90m❯ Pulling the latest state from the remote database..\x1b[0m`)

    const migrationFiles: {filePath: string; migrationStatment: any}[] = []

    try {
      for (const crd of Object.values(CRDs)) {
        let migrationStatment = `-- Migration generated by @TOTUNA CLI\n-- Generated at: ${new Date().toISOString()}\n\n`
        const parser = CRDYAMLParsers[`CRDParser_${crd._kind_}_YAML`]
        const diffs = await crd.$getPreviewPlan(parser)

        if (diffs.length === 0) {
          continue
        }

        migrationStatment += diffs.flatMap((diff) => diff.sqlQuery).join('\n')

        const fileSuffix = `${crd._kind_}.sql`

        // Delete file if file suffix already exists
        glob.sync(`${this.rootStore.systemVariables.PUBLIC_MIGRATIONS_PLAN_PATH}/*${fileSuffix}`).forEach((file) => {
          fs.unlinkSync(file)
        })

        migrationFiles.push({
          filePath: `${this.rootStore.systemVariables.PUBLIC_MIGRATIONS_PLAN_PATH}/${+new Date()}-${fileSuffix}`,
          migrationStatment,
        })
      }

      for (const migrationFile of migrationFiles) {
        fs.mkdirSync(path.dirname(migrationFile.filePath), {recursive: true})
        fs.writeFileSync(migrationFile.filePath, migrationFile.migrationStatment)
        this.log(`Migration plan file created at: ${migrationFile.filePath}`)
      }

      if (migrationFiles.length === 0) {
        this.log('No differences found between the local files and the remote database. 🎉')
      }

      return migrationFiles
    } catch (error) {
      throw new Error(`Failed to export: ${error}`, {cause: error})
    }
  }
}
